# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 451)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graph = PlotWidget(self.centralwidget)
        self.graph.setGeometry(QtCore.QRect(420, 70, 381, 351))
        self.graph.setObjectName("graph")
        self.xVariable = QtWidgets.QComboBox(self.centralwidget)
        self.xVariable.setGeometry(QtCore.QRect(420, 10, 191, 22))
        self.xVariable.setObjectName("xVariable")
        self.spinGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.spinGroupBox.setGeometry(QtCore.QRect(10, 10, 231, 281))
        self.spinGroupBox.setObjectName("spinGroupBox")
        self.valueD = QtWidgets.QDoubleSpinBox(self.spinGroupBox)
        self.valueD.setGeometry(QtCore.QRect(50, 20, 62, 21))
        self.valueD.setDecimals(3)
        self.valueD.setMinimum(-1000.0)
        self.valueD.setMaximum(1000.0)
        self.valueD.setProperty("value", 6.45)
        self.valueD.setObjectName("valueD")
        self.label_20 = QtWidgets.QLabel(self.spinGroupBox)
        self.label_20.setGeometry(QtCore.QRect(120, 20, 41, 21))
        self.label_20.setObjectName("label_20")
        self.valueE = QtWidgets.QDoubleSpinBox(self.spinGroupBox)
        self.valueE.setGeometry(QtCore.QRect(50, 40, 62, 21))
        self.valueE.setDecimals(3)
        self.valueE.setMinimum(-1000.0)
        self.valueE.setMaximum(1000.0)
        self.valueE.setProperty("value", -0.645)
        self.valueE.setObjectName("valueE")
        self.label_13 = QtWidgets.QLabel(self.spinGroupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.spinGroupBox)
        self.label_14.setGeometry(QtCore.QRect(10, 40, 41, 21))
        self.label_14.setObjectName("label_14")
        self.label2 = QtWidgets.QLabel(self.spinGroupBox)
        self.label2.setGeometry(QtCore.QRect(120, 40, 41, 21))
        self.label2.setObjectName("label2")
        self.valueJ = QtWidgets.QDoubleSpinBox(self.spinGroupBox)
        self.valueJ.setGeometry(QtCore.QRect(160, 20, 62, 21))
        self.valueJ.setMaximum(100000.0)
        self.valueJ.setSingleStep(10.0)
        self.valueJ.setObjectName("valueJ")
        self.valueX = QtWidgets.QDoubleSpinBox(self.spinGroupBox)
        self.valueX.setGeometry(QtCore.QRect(160, 40, 62, 21))
        self.valueX.setMaximum(1000.0)
        self.valueX.setProperty("value", 6.45)
        self.valueX.setObjectName("valueX")
        self.valueB = QtWidgets.QDoubleSpinBox(self.spinGroupBox)
        self.valueB.setGeometry(QtCore.QRect(160, 70, 62, 22))
        self.valueB.setMaximum(100000.0)
        self.valueB.setSingleStep(5.0)
        self.valueB.setObjectName("valueB")
        self.label3 = QtWidgets.QLabel(self.spinGroupBox)
        self.label3.setGeometry(QtCore.QRect(120, 70, 41, 21))
        self.label3.setObjectName("label3")
        self.sliderAlpha = QtWidgets.QSlider(self.spinGroupBox)
        self.sliderAlpha.setGeometry(QtCore.QRect(50, 190, 111, 22))
        self.sliderAlpha.setMaximum(360)
        self.sliderAlpha.setOrientation(QtCore.Qt.Horizontal)
        self.sliderAlpha.setObjectName("sliderAlpha")
        self.label_21 = QtWidgets.QLabel(self.spinGroupBox)
        self.label_21.setGeometry(QtCore.QRect(10, 190, 31, 21))
        self.label_21.setObjectName("label_21")
        self.sliderTheta = QtWidgets.QSlider(self.spinGroupBox)
        self.sliderTheta.setGeometry(QtCore.QRect(50, 100, 111, 22))
        self.sliderTheta.setMaximum(360)
        self.sliderTheta.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTheta.setObjectName("sliderTheta")
        self.label_22 = QtWidgets.QLabel(self.spinGroupBox)
        self.label_22.setGeometry(QtCore.QRect(10, 100, 31, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.spinGroupBox)
        self.label_23.setGeometry(QtCore.QRect(10, 130, 31, 21))
        self.label_23.setObjectName("label_23")
        self.sliderPhi = QtWidgets.QSlider(self.spinGroupBox)
        self.sliderPhi.setGeometry(QtCore.QRect(50, 130, 111, 22))
        self.sliderPhi.setMaximum(360)
        self.sliderPhi.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPhi.setObjectName("sliderPhi")
        self.label_24 = QtWidgets.QLabel(self.spinGroupBox)
        self.label_24.setGeometry(QtCore.QRect(10, 60, 101, 41))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.spinGroupBox)
        self.label_25.setGeometry(QtCore.QRect(10, 160, 211, 21))
        self.label_25.setObjectName("label_25")
        self.sliderBeta = QtWidgets.QSlider(self.spinGroupBox)
        self.sliderBeta.setGeometry(QtCore.QRect(50, 220, 111, 22))
        self.sliderBeta.setMaximum(360)
        self.sliderBeta.setOrientation(QtCore.Qt.Horizontal)
        self.sliderBeta.setObjectName("sliderBeta")
        self.sliderGamma = QtWidgets.QSlider(self.spinGroupBox)
        self.sliderGamma.setGeometry(QtCore.QRect(50, 250, 111, 22))
        self.sliderGamma.setMaximum(360)
        self.sliderGamma.setOrientation(QtCore.Qt.Horizontal)
        self.sliderGamma.setObjectName("sliderGamma")
        self.label_26 = QtWidgets.QLabel(self.spinGroupBox)
        self.label_26.setGeometry(QtCore.QRect(10, 220, 31, 21))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.spinGroupBox)
        self.label_27.setGeometry(QtCore.QRect(10, 250, 41, 21))
        self.label_27.setObjectName("label_27")
        self.valueTheta = QtWidgets.QSpinBox(self.spinGroupBox)
        self.valueTheta.setGeometry(QtCore.QRect(170, 100, 51, 22))
        self.valueTheta.setMaximum(360)
        self.valueTheta.setObjectName("valueTheta")
        self.valuePhi = QtWidgets.QSpinBox(self.spinGroupBox)
        self.valuePhi.setGeometry(QtCore.QRect(170, 130, 51, 22))
        self.valuePhi.setMaximum(360)
        self.valuePhi.setObjectName("valuePhi")
        self.valueAlpha = QtWidgets.QSpinBox(self.spinGroupBox)
        self.valueAlpha.setGeometry(QtCore.QRect(170, 190, 51, 22))
        self.valueAlpha.setMaximum(360)
        self.valueAlpha.setObjectName("valueAlpha")
        self.valueBeta = QtWidgets.QSpinBox(self.spinGroupBox)
        self.valueBeta.setGeometry(QtCore.QRect(170, 220, 51, 22))
        self.valueBeta.setMaximum(360)
        self.valueBeta.setObjectName("valueBeta")
        self.valueGamma = QtWidgets.QSpinBox(self.spinGroupBox)
        self.valueGamma.setGeometry(QtCore.QRect(170, 250, 51, 22))
        self.valueGamma.setMaximum(360)
        self.valueGamma.setObjectName("valueGamma")
        self.ratesGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ratesGroupBox.setGeometry(QtCore.QRect(250, 10, 161, 281))
        self.ratesGroupBox.setObjectName("ratesGroupBox")
        self.label = QtWidgets.QLabel(self.ratesGroupBox)
        self.label.setGeometry(QtCore.QRect(50, 80, 31, 21))
        self.label.setObjectName("label")
        self.valueKS = QtWidgets.QDoubleSpinBox(self.ratesGroupBox)
        self.valueKS.setGeometry(QtCore.QRect(90, 20, 62, 21))
        self.valueKS.setDecimals(4)
        self.valueKS.setMaximum(100000.0)
        self.valueKS.setSingleStep(0.01)
        self.valueKS.setProperty("value", 0.0625)
        self.valueKS.setObjectName("valueKS")
        self.valueKD = QtWidgets.QDoubleSpinBox(self.ratesGroupBox)
        self.valueKD.setGeometry(QtCore.QRect(90, 40, 62, 21))
        self.valueKD.setDecimals(4)
        self.valueKD.setMaximum(100000.0)
        self.valueKD.setProperty("value", 0.1)
        self.valueKD.setObjectName("valueKD")
        self.valueKTTA = QtWidgets.QDoubleSpinBox(self.ratesGroupBox)
        self.valueKTTA.setGeometry(QtCore.QRect(90, 60, 62, 21))
        self.valueKTTA.setMaximum(100000.0)
        self.valueKTTA.setProperty("value", 1.0)
        self.valueKTTA.setObjectName("valueKTTA")
        self.valueKSF = QtWidgets.QDoubleSpinBox(self.ratesGroupBox)
        self.valueKSF.setGeometry(QtCore.QRect(90, 80, 62, 21))
        self.valueKSF.setDecimals(1)
        self.valueKSF.setMaximum(100000.0)
        self.valueKSF.setSingleStep(10.0)
        self.valueKSF.setProperty("value", 100.0)
        self.valueKSF.setObjectName("valueKSF")
        self.valueK_SF = QtWidgets.QDoubleSpinBox(self.ratesGroupBox)
        self.valueK_SF.setGeometry(QtCore.QRect(90, 100, 62, 21))
        self.valueK_SF.setDecimals(1)
        self.valueK_SF.setMaximum(100000.0)
        self.valueK_SF.setSingleStep(10.0)
        self.valueK_SF.setProperty("value", 100.0)
        self.valueK_SF.setObjectName("valueK_SF")
        self.valueKTS = QtWidgets.QDoubleSpinBox(self.ratesGroupBox)
        self.valueKTS.setGeometry(QtCore.QRect(90, 120, 62, 21))
        self.valueKTS.setMaximum(100000.0)
        self.valueKTS.setProperty("value", 10.0)
        self.valueKTS.setObjectName("valueKTS")
        self.valueKTF = QtWidgets.QDoubleSpinBox(self.ratesGroupBox)
        self.valueKTF.setGeometry(QtCore.QRect(90, 140, 62, 21))
        self.valueKTF.setMaximum(100000.0)
        self.valueKTF.setProperty("value", 5.0)
        self.valueKTF.setObjectName("valueKTF")
        self.valueKTFfactor = QtWidgets.QDoubleSpinBox(self.ratesGroupBox)
        self.valueKTFfactor.setGeometry(QtCore.QRect(90, 160, 62, 22))
        self.valueKTFfactor.setMaximum(100000.0)
        self.valueKTFfactor.setProperty("value", 2.0)
        self.valueKTFfactor.setObjectName("valueKTFfactor")
        self.checkBoxKTFfactor = QtWidgets.QCheckBox(self.ratesGroupBox)
        self.checkBoxKTFfactor.setGeometry(QtCore.QRect(10, 160, 81, 21))
        self.checkBoxKTFfactor.setChecked(True)
        self.checkBoxKTFfactor.setObjectName("checkBoxKTFfactor")
        self.label_2 = QtWidgets.QLabel(self.ratesGroupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 31, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.ratesGroupBox)
        self.label_3.setGeometry(QtCore.QRect(50, 120, 31, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.ratesGroupBox)
        self.label_4.setGeometry(QtCore.QRect(50, 140, 31, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.ratesGroupBox)
        self.label_5.setGeometry(QtCore.QRect(50, 20, 31, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.ratesGroupBox)
        self.label_6.setGeometry(QtCore.QRect(50, 40, 31, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.ratesGroupBox)
        self.label_7.setGeometry(QtCore.QRect(50, 60, 31, 21))
        self.label_7.setObjectName("label_7")
        self.valueKRISC = QtWidgets.QDoubleSpinBox(self.ratesGroupBox)
        self.valueKRISC.setGeometry(QtCore.QRect(90, 180, 62, 21))
        self.valueKRISC.setDecimals(1)
        self.valueKRISC.setMaximum(100000.0)
        self.valueKRISC.setSingleStep(100.0)
        self.valueKRISC.setProperty("value", 5000.0)
        self.valueKRISC.setObjectName("valueKRISC")
        self.label_8 = QtWidgets.QLabel(self.ratesGroupBox)
        self.label_8.setGeometry(QtCore.QRect(50, 180, 31, 21))
        self.label_8.setObjectName("label_8")
        self.valueKIC1 = QtWidgets.QDoubleSpinBox(self.ratesGroupBox)
        self.valueKIC1.setGeometry(QtCore.QRect(90, 210, 62, 21))
        self.valueKIC1.setMaximum(100000.0)
        self.valueKIC1.setProperty("value", 17.0)
        self.valueKIC1.setObjectName("valueKIC1")
        self.valueKIC2 = QtWidgets.QDoubleSpinBox(self.ratesGroupBox)
        self.valueKIC2.setGeometry(QtCore.QRect(90, 230, 62, 21))
        self.valueKIC2.setMaximum(100000.0)
        self.valueKIC2.setProperty("value", 12.0)
        self.valueKIC2.setObjectName("valueKIC2")
        self.valueKIC21 = QtWidgets.QDoubleSpinBox(self.ratesGroupBox)
        self.valueKIC21.setGeometry(QtCore.QRect(90, 250, 62, 21))
        self.valueKIC21.setMaximum(100000.0)
        self.valueKIC21.setProperty("value", 8.0)
        self.valueKIC21.setObjectName("valueKIC21")
        self.label_9 = QtWidgets.QLabel(self.ratesGroupBox)
        self.label_9.setGeometry(QtCore.QRect(50, 210, 31, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.ratesGroupBox)
        self.label_10.setGeometry(QtCore.QRect(50, 230, 31, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.ratesGroupBox)
        self.label_11.setGeometry(QtCore.QRect(50, 250, 31, 21))
        self.label_11.setObjectName("label_11")
        self.gaplawGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.gaplawGroupBox.setGeometry(QtCore.QRect(10, 290, 401, 91))
        self.gaplawGroupBox.setObjectName("gaplawGroupBox")
        self.valueA = QtWidgets.QDoubleSpinBox(self.gaplawGroupBox)
        self.valueA.setGeometry(QtCore.QRect(60, 40, 62, 21))
        self.valueA.setMaximum(1000000.0)
        self.valueA.setSingleStep(100.0)
        self.valueA.setProperty("value", 4900.0)
        self.valueA.setObjectName("valueA")
        self.valueGGamma = QtWidgets.QDoubleSpinBox(self.gaplawGroupBox)
        self.valueGGamma.setGeometry(QtCore.QRect(60, 60, 62, 21))
        self.valueGGamma.setDecimals(3)
        self.valueGGamma.setMaximum(1000.0)
        self.valueGGamma.setSingleStep(0.01)
        self.valueGGamma.setProperty("value", 0.845)
        self.valueGGamma.setObjectName("valueGGamma")
        self.valueEvib = QtWidgets.QDoubleSpinBox(self.gaplawGroupBox)
        self.valueEvib.setGeometry(QtCore.QRect(180, 40, 62, 21))
        self.valueEvib.setDecimals(3)
        self.valueEvib.setMaximum(100.0)
        self.valueEvib.setSingleStep(0.01)
        self.valueEvib.setProperty("value", 0.17)
        self.valueEvib.setObjectName("valueEvib")
        self.valueT = QtWidgets.QDoubleSpinBox(self.gaplawGroupBox)
        self.valueT.setGeometry(QtCore.QRect(180, 60, 62, 21))
        self.valueT.setDecimals(1)
        self.valueT.setMaximum(1000.0)
        self.valueT.setProperty("value", 293.0)
        self.valueT.setObjectName("valueT")
        self.label_16 = QtWidgets.QLabel(self.gaplawGroupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 40, 61, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.gaplawGroupBox)
        self.label_17.setGeometry(QtCore.QRect(10, 60, 61, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.gaplawGroupBox)
        self.label_18.setGeometry(QtCore.QRect(130, 40, 61, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.gaplawGroupBox)
        self.label_19.setGeometry(QtCore.QRect(130, 60, 31, 21))
        self.label_19.setObjectName("label_19")
        self.checkBoxEnergyGapLaw = QtWidgets.QCheckBox(self.gaplawGroupBox)
        self.checkBoxEnergyGapLaw.setGeometry(QtCore.QRect(10, 10, 361, 31))
        self.checkBoxEnergyGapLaw.setChecked(True)
        self.checkBoxEnergyGapLaw.setObjectName("checkBoxEnergyGapLaw")
        self.valueET1 = QtWidgets.QDoubleSpinBox(self.gaplawGroupBox)
        self.valueET1.setGeometry(QtCore.QRect(330, 40, 62, 21))
        self.valueET1.setDecimals(3)
        self.valueET1.setMaximum(100.0)
        self.valueET1.setSingleStep(0.01)
        self.valueET1.setProperty("value", 1.14)
        self.valueET1.setObjectName("valueET1")
        self.valueET2 = QtWidgets.QDoubleSpinBox(self.gaplawGroupBox)
        self.valueET2.setGeometry(QtCore.QRect(330, 60, 62, 21))
        self.valueET2.setDecimals(3)
        self.valueET2.setMaximum(100.0)
        self.valueET2.setSingleStep(0.01)
        self.valueET2.setProperty("value", 2.43)
        self.valueET2.setObjectName("valueET2")
        self.label_28 = QtWidgets.QLabel(self.gaplawGroupBox)
        self.label_28.setGeometry(QtCore.QRect(250, 40, 71, 21))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.gaplawGroupBox)
        self.label_29.setGeometry(QtCore.QRect(250, 60, 71, 21))
        self.label_29.setObjectName("label_29")
        self.yVariable = QtWidgets.QComboBox(self.centralwidget)
        self.yVariable.setGeometry(QtCore.QRect(620, 10, 181, 22))
        self.yVariable.setObjectName("yVariable")
        self.saveParamsButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveParamsButton.setGeometry(QtCore.QRect(220, 390, 91, 31))
        self.saveParamsButton.setObjectName("saveParamsButton")
        self.saveDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveDataButton.setGeometry(QtCore.QRect(320, 390, 91, 31))
        self.saveDataButton.setObjectName("saveDataButton")
        self.showModelButton = QtWidgets.QPushButton(self.centralwidget)
        self.showModelButton.setGeometry(QtCore.QRect(10, 390, 101, 31))
        self.showModelButton.setObjectName("showModelButton")
        self.loadParamsButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadParamsButton.setGeometry(QtCore.QRect(120, 390, 91, 31))
        self.loadParamsButton.setObjectName("loadParamsButton")
        self.valueXmin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.valueXmin.setGeometry(QtCore.QRect(450, 40, 101, 22))
        self.valueXmin.setDecimals(6)
        self.valueXmin.setMaximum(1000000.0)
        self.valueXmin.setObjectName("valueXmin")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(420, 40, 31, 21))
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(560, 40, 31, 21))
        self.label_15.setObjectName("label_15")
        self.valueXmax = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.valueXmax.setGeometry(QtCore.QRect(600, 40, 101, 22))
        self.valueXmax.setDecimals(6)
        self.valueXmax.setMaximum(1000000.0)
        self.valueXmax.setProperty("value", 1.0)
        self.valueXmax.setObjectName("valueXmax")
        self.checkBoxLogx = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxLogx.setGeometry(QtCore.QRect(740, 40, 51, 21))
        self.checkBoxLogx.setObjectName("checkBoxLogx")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "spinstats GUI"))
        self.spinGroupBox.setTitle(_translate("MainWindow", "spin Hamiltonian parameters"))
        self.label_20.setText(_translate("MainWindow", "J (ueV)"))
        self.label_13.setText(_translate("MainWindow", "D (ueV)"))
        self.label_14.setText(_translate("MainWindow", "E (ueV)"))
        self.label2.setText(_translate("MainWindow", "X (neV)"))
        self.label3.setText(_translate("MainWindow", "B (mT)"))
        self.label_21.setText(_translate("MainWindow", "alpha"))
        self.label_22.setText(_translate("MainWindow", "theta"))
        self.label_23.setText(_translate("MainWindow", "phi"))
        self.label_24.setText(_translate("MainWindow", "magnetic field"))
        self.label_25.setText(_translate("MainWindow", "relative molecular orientation"))
        self.label_26.setText(_translate("MainWindow", "beta"))
        self.label_27.setText(_translate("MainWindow", "gamma"))
        self.ratesGroupBox.setTitle(_translate("MainWindow", "rate constants (per ns)"))
        self.label.setText(_translate("MainWindow", "kSF"))
        self.checkBoxKTFfactor.setText(_translate("MainWindow", "kTF = kTS / "))
        self.label_2.setText(_translate("MainWindow", "k_SF"))
        self.label_3.setText(_translate("MainWindow", "kTS"))
        self.label_4.setText(_translate("MainWindow", "kTF"))
        self.label_5.setText(_translate("MainWindow", "kS"))
        self.label_6.setText(_translate("MainWindow", "kD"))
        self.label_7.setText(_translate("MainWindow", "kTTA"))
        self.label_8.setText(_translate("MainWindow", "kRISC"))
        self.label_9.setText(_translate("MainWindow", "kIC1"))
        self.label_10.setText(_translate("MainWindow", "kIC2"))
        self.label_11.setText(_translate("MainWindow", "kIC21"))
        self.gaplawGroupBox.setTitle(_translate("MainWindow", "energy gap law parameters"))
        self.label_16.setText(_translate("MainWindow", "A (per ns)"))
        self.label_17.setText(_translate("MainWindow", "gamma"))
        self.label_18.setText(_translate("MainWindow", "Evib (eV)"))
        self.label_19.setText(_translate("MainWindow", "T (K)"))
        self.checkBoxEnergyGapLaw.setText(_translate("MainWindow", "use energy gap law for internal conversion rates"))
        self.label_28.setText(_translate("MainWindow", "T1 energy (eV)"))
        self.label_29.setText(_translate("MainWindow", "T2 energy (eV)"))
        self.saveParamsButton.setText(_translate("MainWindow", "save parameters"))
        self.saveDataButton.setText(_translate("MainWindow", "save plot data"))
        self.showModelButton.setText(_translate("MainWindow", "show rate model"))
        self.loadParamsButton.setText(_translate("MainWindow", "load parameters"))
        self.label_12.setText(_translate("MainWindow", "x min"))
        self.label_15.setText(_translate("MainWindow", "x max"))
        self.checkBoxLogx.setText(_translate("MainWindow", "log x"))

from pyqtgraph import PlotWidget
